version: '2.6.1'

services:
  web:
    build: .
    command: > 
      bash -c " cd dev &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py test &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/src
    ports:
      - 8000:8000
